import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import Footer from "./components/footer/footer";
import Header from "./components/header/header";

import './main.css'
const roboto = Roboto({
  weight: '400',
  subsets: ["latin"],

});

export const metadata: Metadata = {
  title: "Stenoprint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header></Header>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}